---
- hosts: servers
  gather_facts: no
  sudo: yes

  tasks:
    - name: ensure user exists
      user:
        name: dev
        state: present
        home: /home/dev
        move_home: yes
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: /home/dev/.ssh/id_rsa
        comment: 'Developer User'

    - name: ensure SSH keys exist for user
      authorized_key:
        user: dev
        key: "https://github.com/{{ item }}.keys"
        state: present
      with_items:
        - "{{ github_usernames }}"
      when: github_usernames is defined

    - name: creating application directory ( /var/www )
      file:
        state: directory
        owner: dev
        recurse: yes
        path: /var/www
        mode: '0755'
